apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-petclinic-ns-sa
  namespace: spring-petclinic
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-petclinic-ns-role
  namespace: spring-petclinic
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-petclinic-ns-role-binding
  namespace: spring-petclinic
subjects:
- kind: ServiceAccount
  name: spring-petclinic-ns-sa
  namespace: spring-petclinic
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-petclinic-ns-role
